//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public string custFirstName { get; set; }
        public string custLastName { get; set; }
        public string custAddress { get; set; }
        public string custEmail { get; set; }
        public string custPhone { get; set; }
    }
}
