//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public System.DateTime transDate { get; set; }
        public decimal transGrossTotal { get; set; }
        public decimal transTax { get; set; }
        public decimal transDiscount { get; set; }
        public decimal transNetTotal { get; set; }
    }
}
